- src/Model/SourceCollection.php
was written for easy automated testing
> added get() function to access specific keys

- src/FileExtractor/BladeFileExtractor.php
- tests/Functional/BladeTest.php
- tests/Resources/Blade/lang.blade.php
- tests/Resources/Blade/trans_choice.blade.php
This will fix #1 
Ping @TobyRyuk, What do you think?
> Added Blade extractor

- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Functional/Visitor/Php/Symfony/FormTypePlaceholderTest.php
- tests/Resources/Php/Symfony/PlaceholderFormType.php
Ping @rbaarsma, what do you think?
> Added placeholder extractor

- composer.json
- phpunit.xml.dist
- src/Annotation/Ignore.php
- src/Model/Error.php
- src/Model/SourceCollection.php
- src/Visitor/BaseVisitor.php
- src/Visitor/Php/Symfony/FormTypeChoices.php
- src/Visitor/Php/Symfony/FormTypeLabelExplicit.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Functional/Visitor/Php/Symfony/FormTypeChoicesTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypeLabelExplicitTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypePlaceholderTest.php
- tests/Resources/Php/Symfony/ExplicitLabelType.php
- tests/Resources/Php/Symfony/PlaceholderFormErrorType.php
- tests/Resources/Php/Symfony/SimpleChoiceSymfony3xErrorType.php
- tests/bootstrap.php
> Support for errors

- tests/Functional/Visitor/Php/Symfony/ContainerAwareTransTest.php
- tests/Resources/Php/Symfony/ContainerAwareTrans.php
Added some more tests to verify issues #28 and #29. The issues does not seam to be related to the extractor library since the code passes the tests.
> Added test code for issue #28 and #29

- composer.json
- src/Visitor/Php/Symfony/FormTypeInvalidMessage.php
- src/Visitor/Php/Symfony/ValidationAnnotation.php
- tests/Functional/Visitor/Php/Symfony/FormTypeInvalidMessageTest.php
- tests/Functional/Visitor/Php/Symfony/ValidationAnnotationTest.php
- tests/Resources/Php/Symfony/FormInvalidMessage.php
- tests/Resources/Php/Symfony/ValidatorAnnotation.php
> Validation

- src/Visitor/Php/Symfony/ValidationAnnotation.php
- tests/Functional/Visitor/Php/Symfony/ValidationAnnotationTest.php
- tests/Resources/Php/Symfony/ValidatorAnnotationError.php
> Catch errors better.

- .travis.yml
- Changelog.md
- src/Annotation/Desc.php
- src/Twig/TranslationExtension.php
- src/Visitor/BaseVisitor.php
- src/Visitor/Php/Symfony/ContainerAwareTrans.php
- src/Visitor/Php/Symfony/ContainerAwareTransChoice.php
- src/Visitor/Php/Symfony/FlashMessage.php
- src/Visitor/Php/Symfony/FormTypeEmptyValue.php
- src/Visitor/Php/Symfony/FormTypeInvalidMessage.php
- src/Visitor/Php/Symfony/FormTypeLabelExplicit.php
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- src/Visitor/Php/Symfony/ValidationAnnotation.php
- src/Visitor/Twig/Worker.php
- tests/Functional/Visitor/Php/DescriptionTest.php
- tests/Functional/Visitor/Twig/TranslationFilterTest.php
- tests/Functional/Visitor/Twig/TwigEnvironmentFactory.php
- tests/Resources/Github/Issue_62.php
- tests/Resources/Php/Symfony/DescriptionType.php
- tests/Resources/Twig/TranslationFilter/desc-error.html.twig
- tests/Resources/Twig/TranslationFilter/desc.html.twig
- tests/Smoke/AllExtractorsTest.php
> Adding support for @Desc annotation

- src/Visitor/Php/Symfony/ValidationAnnotation.php
addError does not accept those parameters
> Remove undefined arguments

- .travis.yml
- composer.json
- src/Visitor/Php/SourceLocationContainerVisitor.php
- src/Visitor/Php/Symfony/ContainerAwareTrans.php
- src/Visitor/Php/Symfony/ContainerAwareTransChoice.php
- src/Visitor/Php/Symfony/FlashMessage.php
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- tests/Functional/Visitor/Php/Symfony/FormTypeLabelTest.php
> Add support for nikic/php-parser:^4

- src/Visitor/BaseVisitor.php
- src/Visitor/Php/Symfony/AbstractFormType.php
- src/Visitor/Php/Symfony/FormTypeChoices.php
- src/Visitor/Php/Symfony/FormTypeLabelExplicit.php
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- tests/Resources/Github/issue_82.php
- tests/Smoke/AllExtractorsTest.php
> Respect the global 'translation_domain'

- src/Visitor/Php/SourceLocationContainerVisitor.php
- src/Visitor/Php/Symfony/AbstractFormType.php
The build broke when I was merging too many PRs at the same time. 
This is a fix related to nikic/php-parser:4.
> Fixed broken build

- Changelog.md
> Prepare for 1.5.0

- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Resources/Github/Issue_101.php
- tests/Resources/Php/Symfony/PlaceholderFormType.php
> FormTypePlaceholder: fix issue with non array attr (function call)

- Changelog.md
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- tests/Resources/Github/Issue_104.php
> Fatal Error from FormTypeImplicit when using method call from variable

- src/Visitor/Php/Symfony/FormTrait.php
- src/Visitor/Php/Symfony/FormTypeHelp.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
As discussed in #113, try to stop node checking.
> Stop nodes check

- src/Visitor/Php/Symfony/FlashMessage.php
- tests/Resources/Github/Issue_101.php
- tests/Resources/Github/Issue_104.php
- tests/Resources/Github/Issue_108.php
- tests/Resources/Github/Issue_109.php
- tests/Resources/Github/Issue_111.php
- tests/Resources/Github/issue_82.php
- tests/Resources/Github/issue_96.php
> Make sure we always use a string

- src/Visitor/Php/Symfony/ContainerAwareTransChoice.php
- tests/Resources/Php/Symfony/ContainerAwareTransChoice.php
This PR adds a failing test and a fix for an issue when using transChoice with a variable.
It is very similar to #147
> fixed error when using variable in transChoice

- .github/workflows/static.yml
> Update image used in github actions

- composer.json
- src/Visitor/Php/Knp/Menu/AbstractKnpMenuVisitor.php
- src/Visitor/Php/Knp/Menu/ItemLabel.php
- src/Visitor/Php/Knp/Menu/LinkTitle.php
- tests/Functional/Visitor/Php/Knp/MenuTest.php
- tests/Resources/Php/Knp/Menu.php
- tests/Smoke/AllExtractorsTest.php
This PR adds the extractors proposed in #149
> added Knp extractors

- Changelog.md
> Prepare v2.0.2

- Changelog.md
After #157 is merged that brings PHP 8 support
> Prepare release v2.0.3

- .github/workflows/ci.yml
- .gitignore
- composer.json
- phpunit.xml.dist
Based on the CI config from https://github.com/php-translation/symfony-bundle/blob/75047fd04f6f951dbf223c221ee974856bd59c7b/.github/workflows/ci.yml
> Add GitHub Actions CI config
