- tests/Functional/Visitor/Php/BasePHPVisitorTest.php
Special to more easily debug for the case of creating a resource php file with a different name than the class itself.
> Added exception for the stupid mistake 

- src/TranslationSourceLocationContainer.php
- src/Visitor/Php/SourceLocationContainerExtractor.php
- tests/Functional/Visitor/Php/SourceLocationContainerExtractorTest.php
- tests/Resources/Php/SourceLocationContainer.php
Ping @michelv
This will fix #20
> Add support for a SourceLocation container

- Changelog.md
- composer.json
- src/FileExtractor/TwigFileExtractor.php
- src/Visitor/Twig/TranslationBlock.php
- src/Visitor/Twig/TranslationFilter.php
- src/Visitor/Twig/Twig2TranslationBlock.php
- src/Visitor/Twig/Twig2TranslationFilter.php
- src/Visitor/Twig/WorkerTranslationBlock.php
- src/Visitor/Twig/WorkerTranslationFilter.php
- tests/Functional/Visitor/Twig/TranslationBlockTest.php
- tests/Functional/Visitor/Twig/TranslationFilterTest.php
- tests/Functional/Visitor/Twig/TwigEnvironmentFactory.php
- tests/Smoke/AllExtractorsTest.php
Make sure we support Twig 2.0. The only issue is that the interface for the vistor has changed. We needed a new class for the Twig2.0 visitors.
> Added Twig2 support

- tests/Functional/Visitor/Php/BasePHPVisitorTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypePlaceholderTest.php
> [Bug] Add unit test to demonstrate incorrect child traversal behaviour

- src/Visitor/Php/Symfony/FormTypeChoices.php
- src/Visitor/Php/Symfony/FormTypeLabelExplicit.php
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Functional/Visitor/Php/BasePHPVisitorTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypePlaceholderTest.php
> Do not stop all visitors if FormVisitor fails

- src/Visitor/Php/Symfony/FormTypeEmptyValue.php
- tests/Functional/Visitor/Php/Symfony/FormEmptyValueTest.php
- tests/Resources/Php/Symfony/EmptyValueType.php
> Adding support for "empty_value"

- src/Extractor.php
`phtml` is an extension used commonly in Zend Framework ecosystem to name (partial) views.
> Support for `phtml` extension as PHP files

- src/Visitor/Php/Symfony/FormTypeChoices.php
- tests/Functional/Visitor/Php/Symfony/FormTypeChoicesTest.php
- tests/Resources/Php/Symfony/SimpleChoicePassArrayType.php
At the moment there is an error when passing array variable to a choices option in a symfony forms. I added only test case since I don't have too much time to go deeper into a code.
> Add test for passing choice array variable.

- composer.json
- src/Visitor/Php/Symfony/FormTrait.php
- src/Visitor/Php/Symfony/FormTypeChoices.php
- src/Visitor/Php/Symfony/FormTypeEmptyValue.php
- src/Visitor/Php/Symfony/FormTypeInvalidMessage.php
- src/Visitor/Php/Symfony/FormTypeLabelExplicit.php
- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Functional/Visitor/Php/Symfony/FormEmptyValueTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypeInvalidMessageTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypePlaceholderTest.php
- tests/Resources/Github/Issue_71.php
- tests/Resources/Php/Symfony/FormInvalidMessageType.php
- tests/Smoke/AllExtractorsTest.php
This will fix #71 
Ping @noofaq could you confirm?
> Make sure FormExtracotrs are disabled unless we extract from a form type

- src/Model/SourceLocation.php
- tests/Unit/Model/SourceLocationTest.php
Doing it via array_map would really help here in getting rid boilerplate code, when I already have list of strings as an array stored somewhere.
Without it, I need to do following each time:
```php
public static function getTranslationSourceLocations(): array
{
$out = [];
foreach(self::CHOICES as $choice) {
$out[] = SourceLocation::createHere($choice);
}
return $out;
}
```
instead of 
```php
public static function getTranslationSourceLocations(): array
{
return array_map('\Translation\Extractor\Model\SourceLocation::createHere', self::CHOICES);
}
```
> Support for array_* callback in SourceLocation::createHere

- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Resources/Github/issue_96.php
- tests/Smoke/AllExtractorsTest.php
> Make placeholder respect translation_domain

- Readme.md
`AllExtracotrsTest` to `AllExtractorsTest`
> Fix typo on Readme.md / Found an issue

- src/Visitor/Php/Symfony/FormTrait.php
- src/Visitor/Php/Symfony/FormTypeHelp.php
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- tests/Functional/Visitor/Php/Symfony/FormTypeHelpTest.php
- tests/Resources/Php/Symfony/HelpFormErrorType.php
- tests/Resources/Php/Symfony/HelpFormType.php
Add a new extractor to deal with the `help` attribue available [since sf4.1](https://symfony.com/blog/new-in-symfony-4-1-form-field-help).
Fix https://github.com/php-translation/symfony-bundle/issues/234
> Deal with help in symfony forms

- src/Visitor/Twig/TwigVisitor.php
The visitor will run at every time a new twig file is parsed. Since our visitors do not modify the Nodes we can safely ignore calls to `enterNode` if we not extracting. 
This will fix https://github.com/php-translation/symfony-bundle/issues/224
> Do not run the Twig worker if we are not extracting,

- src/Visitor/Php/Symfony/FormTypeChoices.php
- tests/Resources/Github/Issue_111.php
- tests/Smoke/AllExtractorsTest.php
Hello,
`@ignore` annotation sound to be ignored on choices attribute
```php
$resolver->setDefaults([
/** @Ignore */
'choices' => function (Options $options) {
return array(
'a label' => 'a',
'an other' => 'b'
);
}
]);
```
The visitor try to parse the function (and returns an error).
#112
> FormTypeChoices: @Ignore is ignored on choices

- Changelog.md
- src/Visitor/Php/Symfony/FlashMessage.php
Hey,
I experienced crash in my symfony project when extacting keys. Here is a quick fix that prevents dealing with edge cases. 
Cheers,
Marc
> Prevent crash when getting callerName

- src/Visitor/Php/Symfony/FormTypeLabelImplicit.php
- tests/Functional/Visitor/Php/Symfony/FormTypeLabelImplicitTest.php
- tests/Resources/Php/Symfony/ImplicitLabelType.php
This PR will fix #131 where the extractor crashes when constant are used as options keys
> fixed FormTypeLabelImplicit visitor when constant is used as option key #131

- Changelog.md
- composer.json
According to Changelog:
- Remove support of Twig 1.x
- Remove support of PHP < 7.2
- Remove support of Symfony < 3.4
- Add support of Symfony ^5.0
- Add strict type hinting
> Prepare v2.0.0

- src/Visitor/Php/Symfony/ContainerAwareTrans.php
- tests/Resources/Php/Symfony/ContainerAwareTrans.php
9070899a20694f875b33fc27c2cdfb20fe419c3b introduced strict string on BaseVisitor addLocation method, calls to trans($myVar) should not be added.
> Call to trans with variable must not trigger Exception

- phpstan-baseline.neon
- src/Visitor/Php/Symfony/FormTypePlaceholder.php
- src/Visitor/Php/Symfony/FormTypeTitle.php
- tests/Functional/Visitor/Php/Symfony/FormTypeLabelTest.php
- tests/Functional/Visitor/Php/Symfony/FormTypeTitleTest.php
- tests/Resources/Php/Symfony/TitleFormErrorType.php
- tests/Resources/Php/Symfony/TitleFormType.php
- tests/Smoke/AllExtractorsTest.php
This PR addresses the issue reported in https://github.com/php-translation/symfony-bundle/issues/394
> add extractor for form field titles

- src/Visitor/Twig/TwigVisitor.php
Fix deprecation message in symfony 5.4
```
Method "Twig\NodeVisitor\NodeVisitorInterface::getPriority()" might add "int" as a native return type declaration in the future. Do the same in implementation "Translation\Extractor\Visitor\Twig\TwigVisitor" now to avoid errors or add an explicit @return annotation to suppress this message.
```
> refac: add return type to fix deprecation

- Readme.md
- Travis CI was dropped in favor of GitHub Actions and does not work anymore
- Scrutinizer does not work anymore, the last build was 2 years ago
- SensioLabsInsight was migrated to SymfonyInsight, but there's no this project, it returns 404
> Simplify badges list and other minor README tweaks
